// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKn9YQ-RtDaaaiss54-SCht2U-vkY76Yk',
    appId: '1:870032788640:web:0e3880c85b8472a8ff4dc5',
    messagingSenderId: '870032788640',
    projectId: 'adair-flutter-lib-tester',
    authDomain: 'adair-flutter-lib-tester.firebaseapp.com',
    storageBucket: 'adair-flutter-lib-tester.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeo8SxAVKjhMuCX6akb5B2jF-Xt_JWakg',
    appId: '1:870032788640:android:b78dd89d61f08e95ff4dc5',
    messagingSenderId: '870032788640',
    projectId: 'adair-flutter-lib-tester',
    storageBucket: 'adair-flutter-lib-tester.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-k0J2-kWZCQwgf9MmFkDK6PiPhoMh1OY',
    appId: '1:870032788640:ios:703de4da464a9d35ff4dc5',
    messagingSenderId: '870032788640',
    projectId: 'adair-flutter-lib-tester',
    storageBucket: 'adair-flutter-lib-tester.firebasestorage.app',
    iosBundleId: 'com.cohenadair.adairFlutterLibTester',
  );

}